name: Check generated files up-to-date

on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  check-generated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: npm install
      - run: npm run generate
      - run: npm run prestart
      - run: git diff --exit-code
