name: Run tests

on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  corpus-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run test-corpus
  node-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm test
  rust-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test
  swift-tests:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: swift test
